const ADD_USER = 'ADD_USER'
const SET_USER = 'SET_USER'
const CLEAR_USER = 'CLEAR_USER'
const SET_SELECTED_USER = 'SET_SELECTED_USER'
const CLEAR_SELECTED_USER = 'CLEAR_SELECTED_USER'
const FOLLOW_USER = 'FOLLOW_USER'
const UNFOLLOW_USER = 'UNFOLLOW_USER'

const CREATE_BLEAT = 'CREATE_BLEAT'
const DELETE_BLEAT = 'DELETE_BLEAT'
const LIKE_BLEAT = 'LIKE_BLEAT'
const UNLIKE_BLEAT = 'UNLIKE_BLEAT'
const SET_SELECTED_BLEAT = 'SET_SELECTED_BLEAT'
const CLEAR_SELECTED_BLEAT = 'CLEAR_SELECTED_BLEAT'

const CREATE_COMMENT = 'CREATE_COMMENT'
const DELETE_COMMENT = 'DELETE_COMMENT'
const LIKE_COMMENT = 'LIKE_COMMENT'
const UNLIKE_COMMENT = 'UNLIKE_COMMENT'

const SET_RESULTS = 'SET_RESULTS'

export {
    ADD_USER,
    SET_USER,
    CLEAR_USER,
    SET_SELECTED_USER,
    CLEAR_SELECTED_USER,
    FOLLOW_USER,
    UNFOLLOW_USER,
    CREATE_BLEAT,
    DELETE_BLEAT,
    LIKE_BLEAT,
    UNLIKE_BLEAT,
    SET_SELECTED_BLEAT,
    CLEAR_SELECTED_BLEAT,
    CREATE_COMMENT,
    DELETE_COMMENT,
    LIKE_COMMENT,
    UNLIKE_COMMENT,
    SET_RESULTS
}

