const ADD_USER = 'ADD_USER'
const SET_USER = 'SET_USER'
const CLEAR_USER = 'CLEAR_USER'

const CREATE_BLEAT = 'CREATE_BLEAT'
const DELETE_BLEAT = 'DELETE_BLEAT'

const FOLLOW_USER = 'FOLLOW_USER'
const UNFOLLOW_USER = 'UNFOLLOW_USER'

const SEARCH = 'SEARCH'

export {
    ADD_USER,
    SET_USER,
    CLEAR_USER,
    CREATE_BLEAT,
    DELETE_BLEAT,
    FOLLOW_USER,
    UNFOLLOW_USER,
    SEARCH
}

